using SixLabors.ImageSharp;

namespace Vortex.Bot.Utility.Images;

public class ImageGenerationConfig
{
    public string BackgroundPath => ImageUtility.GetRandOneBotBackground();

    public float FontSize { get; set; } = 36;
    public float TitleFontSize { get; set; } = 70;
    public float SignatureFontSize { get; set; } = 20;

    public int Gap { get; set; } = 20;
    public int CardMargin { get; set; } = 100;
    public int CardTopMargin { get; set; } = 100;
    public int CardBottomMargin { get; set; } = 50;
    public int ContentTopMargin { get; set; } = 20;
    public int ContentBottomMargin { get; set; } = 20;

    public int LineMaxTextLength { get; set; } = 40;

    public string Title { get; set; } = "标题";
    public string Signature { get; set; } = "Generated by Vortex.Bot";
    public long MemberUin { get; set; } = 523321293;

    public Color CardBackgroundColor { get; set; } = Color.FromRgba(255, 255, 255, 230);
    public Color TitleColor { get; set; } = Color.Black;
    public Color SignatureColor { get; set; } = Color.DarkGray;
    public Color FontColor { get; set; } = Color.Black;
    public Color ThicknessColor { get; set; } = Color.DarkGray;

    public int AvatarSize { get; set; } = 200;
    public int AvatarTop { get; set; } = 120;

    public float CardCornerRadius { get; set; } = 60;
    public int MinWidth { get; set; } = 800;
}
